// English Language Strings
window.LANG_EN = {
    "auth": {
        "app_title": "DIGITIVIA AI AGENT",
        "sign_in_google": "Sign in with Google",
        "sign_in_linkedin": "Sign in with LinkedIn",
        "separator_or": "OR",
        "input_email_placeholder": "Email Address",
        "input_password_placeholder": "Password",
        "btn_login": "LOGIN",
        "btn_register": "REGISTER",
        "btn_loading_login": "LOGGING IN...",
        "btn_loading_register": "REGISTERING..."
    },
    "sidebar": {
        "nav_website": "Website Agent",
        "nav_whatsapp": "WhatsApp Agent",
        "nav_messenger": "Messenger Agent",
        "nav_instagram": "Instagram Agent",
        "nav_insights": "Live Insights",
        "nav_inbox": "Live Inbox",
        "nav_leads": "Leads Area",
        "nav_reviews": "Customer Reviews",
        "nav_followups": "Follow-ups",
        "nav_logout": "Logout"
    },
    "top_bar": {
        "btn_pricing": "Pricing",
        "btn_docs": "Docs",
        "btn_help": "Help"
    },
    "agent_config": {
        "btn_connect_channel": "🔗 Connect Channel",
        "label_live": "LIVE",
        "header_role": "Agent Role (System Prompt)",
        "header_tone": "Agent Tone",
        "header_kb": "Knowledge Base (Links)",
        "header_chat_test": "Test Chat Window",
        "warning_title": "⚠️ Caution:",
        "warning_text": "Modifying the system prompt will directly alter the agent's personality and behavior.",
        "btn_locked": "🔒 Locked - Click to Edit",
        "placeholder_prompt": "Define how your agent should behave...",
        "suggestion_customer_service": "✨ Customer Service",
        "suggestion_sales": "🚀 Sales Agent",
        "placeholder_tone": "Select a tone...",
        "options_tone": {
            "professional": "Professional & Formal",
            "friendly": "Friendly & Casual",
            "empathetic": "Empathetic & Helpful",
            "sales": "Sales-Oriented & Persuasive",
            "witty": "Witty & Humorous"
        },
        "placeholder_link": "https://example.com",
        "btn_add_link": "+ Add Another Link",
        "chat_welcome_msg": "Hello! I am the {agent_name}. How can I help?",
        "placeholder_chat_input": "Type a message...",
        "btn_save": "Save Role",
        "btn_save_changes": "Save Changes *",
        "btn_saving": "Saving..."
    },
    "insights": {
        "title": "Live Insights",
        "platform_facebook": "Facebook",
        "platform_instagram": "Instagram",
        "platform_messenger": "Messenger",
        "period_daily": "Daily",
        "period_weekly": "Weekly",
        "period_28days": "28 Days",
        "period_monthly": "Monthly",
        "empty_title": "No Data Available",
        "empty_text": "Connect your platform accounts to see live performance insights and post engagement.",
        "btn_connect": "Connect Insights",
        "section_posts_header": "Recent Posts Performance",
        "loading_posts": "Loading posts...",
        "empty_posts_title": "No Posts Yet",
        "empty_posts_text": "Connect your {platform} account to see your post performance here.",
        "btn_connect_posts": "Connect Posts",
        "error_posts_load": "Failed to load posts",
        "post_card_reach": "Reach",
        "post_card_view": "➜ View Details",
        "no_caption": "No caption",
        "stats": {
            "video_views": "Video Views",
            "video_view_time": "Video View Time",
            "post_engagements": "Post Engagements",
            "unique_reach": "Unique Reach",
            "total_impressions": "Total Impressions",
            "profile_views": "Profile Views",
            "website_clicks": "Website Clicks",
            "total_interactions": "Total Interactions",
            "total_connections": "Total Connections",
            "new_conversations": "New Conversations"
        }
    },
    "inbox": {
        "sidebar_select_platform": "Select Platform",
        "sidebar_loading": "Loading...",
        "sidebar_no_chats": "No chats found.",
        "sidebar_error": "Error loading contacts.",
        "header_select": "Select a conversation",
        "header_chat_with": "Chat with {name}",
        "loading_history": "Loading history...",
        "empty_title": "No Conversations Yet",
        "empty_text": "Connect your social channels to start chatting with your customers in real-time.",
        "btn_connect": "Connect Channels",
        "empty_messages": "No messages yet.",
        "error_loading_messages": "Error loading messages",
        "msg_error_agent": "Error: Could not reach agent.",
        "msg_no_reply": "No reply received."
    },
    "leads": {
        "title": "Leads Area",
        "btn_export_csv": "Export CSV",
        "btn_export_excel": "Export Excel",
        "loading": "Fetching Leads...",
        "empty_search": "No leads found.",
        "error_loading": "Failed to load leads. Check connection.",
        "empty_title": "No Leads Yet",
        "empty_text": "Connect your channels to start capturing leads from conversations.",
        "btn_connect": "Connect Your Channels",
        "status": {
            "qualified": "Qualified",
            "pending": "Pending",
            "new": "New"
        }
    },
    "reviews": {
        "title": "Customer Reviews",
        "btn_connect_google": "Connect Google Reviews",
        "stat_avg": "Average Rating",
        "stat_total": "Total Reviews",
        "stat_positive": "Positive (4-5★)",
        "empty_title": "No Reviews Connected",
        "empty_text": "Link your Google Business profile to monitor and reply to reviews here."
    },
    "followups": {
        "title": "Scheduled Follow-ups",
        "empty_title": "No Scheduled Tasks",
        "empty_text": "When your agents schedule callbacks or follow-ups, they will appear here.",
        "btn_setup": "Set Up Automations"
    },
    "modals": {
        "unlock": {
            "title": "⚠️ Critical Warning",
            "text": "Changing the System Prompt will fundamentally alter how this agent behaves, answers, and interacts.",
            "text_confirm_ask": "Are you sure you want to proceed?",
            "btn_cancel": "Cancel",
            "btn_confirm": "Yes, Unlock Editing"
        },
        "post_detail": {
            "date_label": "Date",
            "caption_default": "Caption text...",
            "stat_likes": "Likes",
            "stat_comments": "Comments",
            "stat_reach": "Reach",
            "section_comments": "RECENT COMMENTS",
            "comments_not_loaded": "Comments not loaded"
        },
        "pricing": {
            "header_title": "Choose Your Plan",
            "header_text": "Scale your AI agents with the perfect plan for your business",
            "plans": {
                "free": "Free",
                "starter": "Starter",
                "growth": "Growth",
                "enterprise": "Enterprise"
            },
            "price_custom": "Custom",
            "period_month": "/month",
            "badge_popular": "POPULAR",
            "features": {
                "msg_100": "100 messages/month",
                "agent_1": "1 AI agent",
                "analytics_basic": "Basic analytics",
                "support_community": "Community support",
                "msg_1000": "1,000 messages/month",
                "agent_2": "2 AI agents",
                "analytics_adv": "Advanced analytics",
                "support_email": "Email support",
                "msg_10000": "10,000 messages/month",
                "agent_4": "4 AI agents",
                "analytics_prio": "Priority analytics",
                "support_prio": "Priority support",
                "integrations_custom": "Custom integrations",
                "msg_unlim": "Unlimited messages",
                "agent_unlim": "Unlimited agents",
                "whitelabel": "White-label options",
                "manager_ded": "Dedicated manager",
                "sla": "SLA guarantee"
            },
            "btn_current": "Current Plan",
            "btn_upgrade": "Upgrade",
            "btn_contact": "Contact Sales"
        },
        "docs": {
            "title": "Documentation & User Guide",
            "sec_start_title": "🚀 Getting Started",
            "sec_start_text": "Welcome to Digitivia AI Agent! This platform allows you to create, manage, and monitor powerful AI agents across multiple communication channels.",
            "sec_config_title": "🤖 Configuring Your Agents",
            "sec_config_text": "Each agent (Website, WhatsApp, Messenger, Instagram) can be customized independently:",
            "sec_config_list_prompt": "<strong>System Prompt:</strong> This is the \"brain\" of your agent. Define its personality, knowledge, and boundaries.",
            "sec_config_list_tone": "<strong>Tone:</strong> Choose how the agent should sound (e.g., Professional, Friendly, Helpful).",
            "sec_config_list_kb": "<strong>Knowledge Base Links:</strong> Add URLs that your agent should use as a reference to answer questions accurately.",
            "tip_label": "Pro Tip:",
            "tip_text": "Be specific in your System Prompt. Instead of \"You are a helpful assistant,\" try \"You are an expert real estate consultant for Acme Realty, specializing in downtown apartments.\"",
            "sec_connect_title": "🔌 Connecting Channels",
            "sec_connect_text": "To start receiving messages, you need to connect your social channels:",
            "sec_connect_list_1": "Go to the specific agent tab in the left sidebar.",
            "sec_connect_list_2": "Click the <strong>\"Connect Channel\"</strong> button.",
            "sec_connect_list_3": "Follow the integration steps (currently requires a consultation for setup).",
            "sec_inbox_title": "📨 Using the Live Inbox & Leads",
            "sec_inbox_list_inbox": "<strong>Live Inbox:</strong> Monitor real-time conversations between your agents and customers. You can step in at any time to take over the chat.",
            "sec_inbox_list_leads": "<strong>Leads Area:</strong> Automatically captures contact details and interests from conversations, allowing you to export or manage your pipeline.",
            "sec_inbox_list_insights": "<strong>Live Insights:</strong> View performance metrics, message volume, and engagement statistics across all platforms.",
            "cta_title": "Need more help?",
            "cta_text": "If you're stuck or need a custom implementation, our team is here to help.",
            "btn_book": "Book Free Consultation"
        },
        "profile": {
            "default_name": "User Name",
            "label_org": "Organization",
            "placeholder_org": "Organization Name",
            "label_plan": "Current Plan",
            "val_free": "Free",
            "btn_save": "Save Organization Name",
            "btn_upgrade": "Upgrade Plan",
            "btn_logout": "Logout"
        },
        "help": {
            "title": "Free Consultation Meeting",
            "text": "Book a 30-minute consultation with our team to help you get the most out of your AI agents.",
            "remaining_prefix": "You have",
            "remaining_suffix": "free consultation(s) remaining",
            "btn_book": "Book Consultation",
            "btn_contact": "Contact Sales"
        }
    },
    "messages": {
        "toast_saved": "Saved Successfully!",
        "toast_fill_login": "Please fill in email and password",
        "toast_login_failed": "Login Failed",
        "toast_reg_success": "Registration successful! Check your email.",
        "toast_reg_failed": "Registration Failed",
        "toast_error_connect": "Error connecting to {provider}",
        "toast_org_empty": "Organization name cannot be empty",
        "toast_session_error": "User session issue. Please reload.",
        "toast_org_updated": "Organization name updated!",
        "toast_stripe_soon": "Stripe checkout for \"{plan}\" plan coming soon!",
        "toast_no_org": "No Organization Found. Please contact admin.",
        "toast_saving_error": "Error saving data: ",
        "toast_activated": "Activated {agent}",
        "toast_deactivated": "Deactivated {agent}",
        "toast_status_fail": "Failed to update status",
        "toast_no_leads_export": "No leads to export",
        "loading_config": "Fetching Agent Configurations..."
    }
};
